# Generated by Django 4.2.3 on 2023-07-16 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_remove_news_headline'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='headline',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
