# Generated by Django 4.2.3 on 2023-07-17 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_news_headline'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='dislike_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='news',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
    ]
