# Generated by Django 4.2.3 on 2023-07-26 06:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0010_alter_comment_is_visible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='like_count',
        ),
        migrations.AddField(
            model_name='news',
            name='like_count',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
