# Generated by Django 4.2.3 on 2023-08-05 18:01

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_rename_dislike_count_news_dislikes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='editors_pick',
        ),
        migrations.AddField(
            model_name='news',
            name='news_option',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('NN', 'Normal News'), ('BN', 'Breaking News'), ('EP', "Editors' Pick"), ('F', 'Features'), ('CN', 'Carousel News'), ('CaN', 'Card News')], default='NN', max_length=40),
        ),
    ]
