# Generated by Django 4.2.3 on 2023-08-28 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0016_planfeatures_plan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planfeatures',
            options={'verbose_name_plural': 'Plan Features'},
        ),
        migrations.AlterField(
            model_name='plan',
            name='feature',
            field=models.ManyToManyField(blank=True, to='news.planfeatures'),
        ),
    ]
